# Content for the activity detail pages.
# Descriptions are verbatim from the original pages; names, leads and keywords are from
# the Projects-page copy. Photos are exactly the ones each original page used (no mixing).
# A photo key without "/" lives in assets/images/ais/projects/.

P_SKILLS = ('Participanții au dezvoltat comunicarea, lucrul în echipă, gândirea critică, reflecția, încrederea în sine, '
            'inițiativa, adaptabilitatea, colaborarea interculturală și capacitatea de a-și planifica mai conștient '
            'viitorul educațional și profesional.')
P_STATS = ''  # kept for build.py compatibility (number tiles removed at the user's request)

# Placeholder text for the Impact section (to be replaced with real content)
LOREM_IMPACT = [
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante venenatis dapibus, posuere velit aliquet. Curabitur blandit tempus porttitor, sed posuere consectetur est at lobortis. Donec ullamcorper nulla non metus auctor fringilla.',
    'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.',
    'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet.',
]

BLOG = {
    'InnoVenture': 'https://innoventure-labour-market.blogspot.com/',
    'NextGEN': 'https://nextgen-project.blogspot.com/',
    'LevelUP': 'https://levelup-youth-project.blogspot.com/',
}
CADRU = 'Acreditarea Erasmus+ AIS'
LEVELUP_INTRO = ('În al treilea an, prin LevelUP, AIS a implementat activități dedicate comunității, orientării profesionale și '
                 'planificării propriului parcurs. Participanții au lucrat practic, au colaborat în echipe internaționale și au '
                 'conectat experiența Erasmus+ cu realități locale, comunitare și profesionale.')

ACTIVITIES = {
    'ecoart': dict(
        code='A1', en='You(th) in Business', ro='Tineri în afaceri', program='InnoVenture',
        kicker='InnoVenture · prima mobilitate din anul 1 al acreditării AIS',
        lead='Ai o idee? Aici înveți să o planifici, să o testezi și să o transformi într-un concept real, împreună cu o echipă internațională.',
        kws=['idei', 'lucru în echipă', 'business'],
        tematica='Inițiativă, planificare, lucru în echipă', cadru=CADRU, etapa='Anul 1',
        blog=BLOG['InnoVenture'],
        drive='https://drive.google.com/drive/folders/15gRmOYeoe6KQCIqTq7ULCTQm2HqkMIkv?usp=drive_link',
        results='https://drive.google.com/drive/folders/14iV8IuaY-JcefswxMmFg6xl8hceJbl-V?usp=sharing',
        desc=['În primul an, prin InnoVenture, activitatea Tineri în afaceri a sprijinit inițiativa, planificarea unei idei, lucrul în echipă și transformarea unei idei într-un concept practic.',
              P_SKILLS],
        extra=LOREM_IMPACT, lorem=True,
        fan=['A1_18', 'A1_09', 'A1_14'],
        photos=[
            ('A1_02', 'Participanți lucrând în echipă la o masă'),
            ('A1_03', 'Participanți într-o sesiune în sala de activități'),
            ('A1_04', 'Sticle de apă și materiale ale proiectului, pe o masă'),
            ('A1_05', 'Participanți așezați în cerc într-o sală cu lambriu din lemn'),
            ('A1_06', 'Panou cu bilețele colorate dintr-o activitate de reflecție'),
            ('A1_07', 'Grupul așezat în cerc într-o sală mare din lemn'),
            ('A1_08', 'Participanți așezați pe bănci, urmărind o activitate'),
            ('A1_09', 'Fotografie de grup cu toți participanții, în aer liber'),
            ('A1_10', 'Desen cu numele proiectului și steagurile țărilor participante'),
            ('A1_11', 'Masă cu preparate tradiționale și steaguri ale țărilor participante'),
            ('A1_12', 'Participanți în cerc, în timpul unui joc în sala de activități'),
            ('A1_13', 'Prezentare proiectată în sala de activități'),
            ('A1_14', 'Participanți zâmbind lângă steagul Poloniei'),
            ('A1_15', 'Participanți lângă o masă cu preparate tradiționale'),
            ('A1_16', 'Grup de participanți în aer liber, cu un castel pe deal în fundal'),
            ('A1_17', 'Selfie de grup lângă un perete cu graffiti'),
            ('A1_18', 'Selfie de grup în curtea unui castel'),
            ('A1_19', 'Clădire istorică cu turn, într-o piață, sub cer albastru'),
            ('A1_20', 'Participanți urmărind o prezentare'),
            ('A1_21', 'Masă cu preparate tradiționale și steagul Spaniei'),
            ('A1_22', 'Participanți lângă o masă cu preparate tradiționale și steaguri'),
        ],
        prev=None,
        next=('fashionforward.html', 'A2', 'You(th) on the Labour Market', 'ais/A2'),
    ),

    'fashionforward': dict(
        code='A2', en='You(th) on the Labour Market', ro='Tinerii pe piața muncii', program='InnoVenture',
        kicker='InnoVenture · pregătirea tinerilor pentru tranziția către piața muncii',
        lead='Pregătire pentru lumea reală: tinerii și-au descoperit punctele forte și au învățat să se prezinte cu încredere pe piața muncii.',
        kws=['angajabilitate', 'comunicare', 'încredere'],
        tematica='Piața muncii, comunicare, auto-prezentare', cadru=CADRU, etapa='Anul 1',
        blog=BLOG['InnoVenture'],
        drive='https://drive.google.com/drive/folders/1A83_w0rXHpQG5K4nXpuavqwdmM7LgKML?usp=drive_link',
        results='https://drive.google.com/drive/folders/1A83_w0rXHpQG5K4nXpuavqwdmM7LgKML?usp=drive_link',
        desc=['În primul an, prin InnoVenture, activitatea Tinerii pe piața muncii a sprijinit pregătirea pentru tranziția către piața muncii, dezvoltarea încrederii, comunicării și capacității de auto-prezentare.',
              P_SKILLS],
        extra=LOREM_IMPACT, lorem=True,
        fan=['A2_02', 'A2_09', 'A2_07'],
        photos=[
            ('A2_02', 'Selfie de grup cu participanții, în fața unei clădiri'),
            ('A2_03', 'Participanți lucrând pe o coală mare de hârtie, la o masă'),
            ('A2_04', 'Participanți în picioare, în cerc, în sala de activități'),
            ('A2_05', 'Participanți discutând sub un foișor din lemn'),
            ('A2_06', 'Participanți într-un joc de echipă, pe pajiște'),
            ('A2_07', 'Grupul în cerc pe o pajiște, sub cer albastru'),
            ('A2_08', 'Participantă citind de pe o foaie, în sala de activități'),
            ('A2_09', 'Participanți pozând amuzant pentru o fotografie de grup, în aer liber'),
            ('A2_10', 'Participanți în aer liber, lângă case cu acoperiș roșu'),
            ('A2_11', 'Masă cu preparate tradiționale și steagul României'),
            ('A2_12', 'Participanți lucrând la laptopuri, pe podea'),
            ('A2_13', 'Participanți într-o activitate, în sala cu lambriu din lemn'),
            ('A2_14', 'Participanți așezați pe bănci, ascultând o prezentare'),
            ('A2_15', 'Participanți lucrând în echipă pe podea, cu laptopuri'),
            ('A2_16', 'Prezentare proiectată într-o sală din lemn'),
            ('A2_17', 'Grupul în cerc pe pajiște, lângă cabane'),
            ('A2_18', 'Activitate în aer liber, la apus'),
            ('A2_19', 'Participanți urmărind o prezentare, seara'),
            ('A2_20', 'Selfie cu trei participanți'),
        ],
        prev=('ecoart.html', 'A1', 'You(th) in Business', 'ais/A1'),
        next=('followyourdrums.html', 'A3', 'YouthPreneurs', 'ais/A3'),
    ),

    'followyourdrums': dict(
        code='A3', en='YouthPreneurs', ro='Tineri antreprenori', program='NextGEN',
        kicker='NextGEN · aprofundarea competențelor prin exerciții practice și lucru internațional',
        lead='Gândește ca un antreprenor: de la idee la pitch, tinerii au construit, testat și prezentat proiecte în echipe internaționale.',
        kws=['antreprenoriat', 'creativitate', 'simulări'],
        tematica='Inițiativă, competențe practice, colaborare', cadru=CADRU, etapa='Anul 2',
        blog=BLOG['NextGEN'],
        drive='https://drive.google.com/drive/folders/1t26lJ0f-gB6s3-MSmJIa1fLzzV7S-lmF?usp=drive_link',
        results='https://drive.google.com/drive/folders/1t26lJ0f-gB6s3-MSmJIa1fLzzV7S-lmF?usp=drive_link',
        desc=['În al doilea an, prin NextGEN, activitatea Tineri antreprenori a aprofundat competențele prin exerciții practice, lucru în echipe internaționale, simulări, prezentări și reflecție.',
              P_SKILLS],
        extra=LOREM_IMPACT, lorem=True,
        fan=['A3_09', 'A3_02', 'A3_06'],
        photos=[
            ('A3_02', 'Fotografie de grup cu participanții, pe zăpadă, cu munții în fundal'),
            ('A3_03', 'Participant vorbind în fața grupului, într-o sală din lemn'),
            ('A3_04', 'Materiale ale proiectului, pe scaune roșii'),
            ('A3_05', 'Participanți în picioare, în timpul unei activități'),
            ('A3_06', 'Echipă prezentând un proiect în fața grupului'),
            ('A3_07', 'Participanți într-un exercițiu de grup, în sala din lemn'),
            ('A3_08', 'Masă cu preparate tradiționale'),
            ('A3_09', 'Selfie cu participanți lângă steagul Turciei'),
            ('A3_10', 'Echipă prezentând despre Polonia, cu proiecție pe ecran'),
            ('A3_11', 'Participanți prezentând un proiect în fața ecranului'),
            ('A3_12', 'Sticle expuse în timpul unei vizite de studiu'),
            ('A3_13', 'Meșter popular în costum tradițional, într-un atelier'),
            ('A3_14', 'Meșter popular lucrând linguri din lemn'),
            ('A3_15', 'Participanți într-o sală mare din lemn, în timpul unei activități'),
            ('A3_16', 'Participanți așezați în cerc, cu materiale pe podea'),
            ('A3_17', 'Participanți lucrând în grupuri mici, pe podea'),
            ('A3_18', 'Participanți lângă o masă cu steagul Turciei'),
            ('A3_19', 'Patru participanți în fața unei clădiri, iarna'),
            ('A3_20', 'Participanți într-o prezentare de costume, în sala de activități'),
            ('A3_21', 'Participanți la o masă, în timpul unei activități'),
            ('A3_22', 'Bilețele colorate cu numele echipelor și ideile de proiect'),
            ('A3_23', 'Participant prezentând, cu un logo proiectat pe ecran'),
            ('A3_24', 'Prezentare proiectată într-o sală întunecată'),
        ],
        prev=('fashionforward.html', 'A2', 'You(th) on the Labour Market', 'ais/A2'),
        next=('aiart2-blog.html', 'A4', 'EmployAbility', 'ais/A4'),
    ),

    'aiart2-blog': dict(
        code='A4', en='EmployAbility', ro='Angajabilitate', program='NextGEN',
        kicker='NextGEN · dezvoltare personală și profesională prin învățare practică',
        lead='Tot ce nu te învață nimeni despre lumea muncii, descoperit prin exerciții practice, feedback și multă reflecție.',
        kws=['competențe', 'carieră', 'dezvoltare personală'],
        tematica='', cadru=CADRU, etapa='Anul 2',
        blog=BLOG['NextGEN'], drive='', results='',
        desc=['În al doilea an, prin NextGEN, activitatea Angajabilitate a aprofundat competențele prin exerciții practice, lucru în echipe internaționale, simulări, prezentări, reflecție și instrumente pentru dezvoltarea personală și profesională.',
              P_SKILLS],
        extra=LOREM_IMPACT, lorem=True,
        fan=['ais/A4_2', 'ais/A4', 'A4_02'],
        photos=[
            ('A4_02', 'Colaj cu fotografii de grup în fața unei clădiri istorice'),
            ('ais/A4', 'Afiș NextGen: EmployAbility, ziua 3, cu fotografii din activitate'),
            ('ais/A4_2', 'Tineri participanți așezați într-un cerc, în aer liber, lângă pădure'),
        ],
        prev=('followyourdrums.html', 'A3', 'YouthPreneurs', 'ais/A3'),
        next=('eye2025.html', 'A6', 'Ready4Work', 'ais/A6'),
    ),

    'eye2025': dict(
        code='A6', en='Ready4Work', ro='Pregătiți pentru muncă', program='LevelUP',
        kicker='LevelUP · conectarea învățării Erasmus+ cu realitățile profesionale',
        lead='Pregătit pentru primul job? După zile pline de provocări practice și întâlniri cu oameni din domeniu, răspunsul devine da.',
        kws=['angajabilitate', 'comunicare', 'experiență practică'],
        tematica='Orientare profesională, comunicare, pregătire', cadru=CADRU, etapa='Anul 3',
        blog=BLOG['LevelUP'], drive='', results='',
        desc=[LEVELUP_INTRO, P_SKILLS],
        extra=LOREM_IMPACT, lorem=True,
        fan=['A6_03', 'A6_12', 'A6_11'],
        photos=[
            ('A6_02', 'Logo cu o carte deschisă și mesajele „The story continues!” și „Together we are stronger!”'),
            ('A6_03', 'Participanți în tricouri verzi, cu steaguri, în aer liber'),
            ('A6_04', 'Participanți dansând în sala din lemn'),
            ('A6_05', 'Colaj: participanți într-o sesiune, în sala cu scaune roșii'),
            ('A6_06', 'Participanți într-o îmbrățișare de grup'),
            ('A6_07', 'Colaj: grupul în oraș și într-o sală de consiliu'),
            ('A6_08', 'Participantă cu cercuri luminoase, în timpul unei activități'),
            ('A6_09', 'Colaj: participanți în discuții, la masă'),
            ('A6_10', 'Statuete și ecran cu „Oscars”, la o seară de premiere'),
            ('A6_11', 'Participanți cu hanorace „You Are Your Own Limit”'),
            ('A6_12', 'Participanți strânși într-o îmbrățișare de grup'),
            ('A6_13', 'Participanți într-o activitate, în sala din lemn'),
            ('A6_14', 'Colaj: grupul în oraș și într-o sală de consiliu'),
        ],
        prev=('aiart2-blog.html', 'A4', 'EmployAbility', 'ais/A4'),
        next=('firstaid-blog.html', 'A7', 'Create Your Own Path', 'ais/A7'),
    ),

    'firstaid-blog': dict(
        code='A7', en='Create Your Own Path', ro='Creează-ți propriul drum', program='LevelUP',
        kicker='LevelUP · planificarea mai conștientă a propriului parcurs',
        lead='Nimeni nu îți poate desena drumul mai bine decât tine. Aici ai primit instrumentele ca să îl planifici cu curaj.',
        kws=['orientare', 'planificare', 'viitor'],
        tematica='Planificare educațională și profesională', cadru=CADRU, etapa='Anul 3',
        blog=BLOG['LevelUP'],
        drive='https://drive.google.com/drive/folders/1xSrJEYoWK_IpxbyzgGKBVSxktIO0BHvH?usp=drive_link',
        results='https://drive.google.com/drive/folders/1xSrJEYoWK_IpxbyzgGKBVSxktIO0BHvH?usp=drive_link',
        desc=[LEVELUP_INTRO, P_SKILLS,
              'Activitățile practice au oferit participanților contexte de învățare prin experiență, colaborare, reflecție și dezvoltarea încrederii în propriile capacități.',
              'Prin lucru în echipă, discuții și reflecție ghidată, participanții și-au consolidat comunicarea, adaptabilitatea, gândirea critică și capacitatea de a conecta învățarea cu situații reale.'],
        extra=LOREM_IMPACT, lorem=True,
        fan=['A7_04', 'A7_06', 'A7_05'],
        photos=[
            ('A7_02', 'Fotografie de grup cu participanții și steagurile țărilor partenere'),
            ('A7_03', 'Logo European Youth Bank (Erasmus+, Horizon, Interreg)'),
            ('A7_04', 'Participanți în tricouri verzi, cu steaguri, în aer liber'),
            ('A7_05', 'Participanți zâmbind în sala de activități'),
            ('A7_06', 'Fotografie de grup în aer liber, cu dealuri în fundal'),
            ('A7_07', 'Participanți în picioare, prezentând în fața grupului'),
            ('A7_08', 'Grupul în aer liber, într-un sat de munte'),
            ('A7_09', 'Fotografie de grup în fața unui autocar'),
            ('A7_10', 'Prezentare proiectată în sala de activități'),
            ('A7_11', 'Participanți discutând la o masă'),
            ('A7_12', 'Participanți lucrând în grupuri, la mese'),
            ('A7_13', 'Participanți la o masă din lemn, pe terasă'),
            ('A7_14', 'Participanți așezați în cerc, în sala cu scaune roșii'),
            ('A7_15', 'Participanți râzând, așezați pe canapele'),
            ('A7_16', 'Steagul Turciei'),
            ('A7_17', 'Steagul Serbiei'),
            ('A7_18', 'Logo Creative Youth Academy, Ungaria'),
            ('A7_19', 'Logo DGT Polska'),
        ],
        prev=('eye2025.html', 'A6', 'Ready4Work', 'ais/A6'),
        next=('razemprzeciwuzaleznieniom.html', 'BOOST', 'BOOST: Your Future Skills', 'banners-simple/boost'),
    ),
}
